# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-29 03:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='todo_job',
            new_name='description',
        ),
        migrations.AddField(
            model_name='todo',
            name='name',
            field=models.CharField(default='', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
