# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-26 05:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='choice_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
