# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-18 08:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='image',
            field=models.ImageField(default=datetime.datetime(2016, 10, 18, 8, 47, 42, 242023, tzinfo=utc), upload_to=''),
            preserve_default=False,
        ),
    ]
