# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-27 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_portfolio_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='portfolio_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
